config/routes.rb
Evalink::Application.routes.draw do

  resources :companies

  get "/expertises/calificar" => "expertises#calificar", :as => "calificar_expertise"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "show_results" => "search#show_results", :as => "search_results"
  get "choose_jobs" => "search#choose_jobs", :as => "choose_jobs"
  get "choose_features" => "search#choose_features", :as => "choose_features"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "users#new"
  resources :users
  resources :sessions
  resources :abilities
  resources :expertises
  resources :validations

  get "sessions/new"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :age, :university, :profession, :job_looking_for
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  belongs_to :company
  
  has_many :abilities
  has_many :expertises
  has_many :votacions

  has_many :validations #como validador, son las validaciones que hace, no las que le hacen
  
  def is_expert?(area)
    expertises.each do |e|
      if e.area == area
        return true
      end
    end
    false
  end

  def has_validated?(ability)
    validations.each do |v|
      if v.ability_id == ability.id
        return true
      end
    end
    false
  end

  def has_voted?(expertise)
    votacions.each do |v|
      if v.expertise_id == expertise.id
        return true
      end
    end
    false
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @query = params[:q]
    @users = User.all
    @found = 0
  end



  def new
    redirect_to current_user if current_user
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to log_in_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @abilities = @user.abilities
    @expertises = @user.expertises
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% @users.each do |u| %>
  <% if "#{u.first_name} #{u.last_name}".include?(@query) %>
    <% @found += 1 %>
    <%= link_to "#{u.first_name} #{u.last_name}", u %>
  <% end %>
<% end %>

<%if @found == 0 %>
  No se encontraron usuarios
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name%>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </p>
   <p>
    <%= f.label :university %><br />
    <%= f.text_field :university %>
  </p>
  <p>
    <%= f.label :profession %><br />
    <%= f.text_field :profession %>
  </p>
   <p>
    <%= f.label :looking_for_job_as %><br />
    <%= f.text_field :job_looking_for %>
  </p>





  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h1>Perfil</h1>


  <p>
    <strong> Nombre:  </strong>
    <%= @user.first_name %>
  </p>
    <p>
    <strong> Apellido:  </strong>
    <%= @user.last_name %>
  </p>
    <p>
    <strong> Edad:  </strong>
    <%= @user.age %>
  </p>
    <p>
    <strong> Universidad:  </strong>
    <%= @user.university %>
  </p>
  <p>
    <strong> Profesion:  </strong>
    <%= @user.profession %>
  </p>  
  <p>
    <strong> Busco trabajo como:  </strong>
    <%= @user.job_looking_for %>
  </p>

    <h2> Mis habilidades</h2>
    <% @abilities.each do |a| %>
      <%= link_to "#{a.name}", a %> 
      <% if a.has_validations? %>
        habilidad validada por experto(s)
        <%end%>
      <br/>
    <% end %>
    <% if @user.id == current_user.id %><br/>
      <%= link_to "Agregar habilidad", new_ability_url %>
    <% end %>



  <br/>
<h2> Empresas </h2>
  <% if @user.id == current_user.id %>
    <% if @user.company %>
      Usted representa a la empresa <%= @user.company.name %> <br/>
      <%= link_to "Buscar candidatos a empleos para #{@user.company.name}", choose_jobs_url %>
    <% else %>
      <%= link_to "Representar empresa", new_company_url %>
    <% end %>
  <% end %>

  <h2> Expertises </h2>
  <div>
    Tener una expertise en un área te permite validad las habilidades de otros usuarios en esa área<br/>
    <% @expertises.each do |e| %>
      <%= link_to "#{e.area}", e %>
    <% end %>


    <br/>
    <% if @user.id == current_user.id %><br/>
      <%= link_to "Agregar expertise", new_expertise_url %>
    <% end %>
  </div>