config/routes.rb
Evalink::Application.routes.draw do

  resources :companies

  get "/expertises/calificar" => "expertises#calificar", :as => "calificar_expertise"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "show_results" => "search#show_results", :as => "search_results"
  get "choose_jobs" => "search#choose_jobs", :as => "choose_jobs"
  get "choose_features" => "search#choose_features", :as => "choose_features"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "users#new"
  resources :users
  resources :sessions
  resources :abilities
  resources :expertises
  resources :validations

  get "sessions/new"

end

app/controllers/expertises_controller.rb
class ExpertisesController < ApplicationController
  # GET /expertises
  # GET /expertises.json
  def index
    @expertises = Expertise.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expertises }
    end
  end

  # GET /expertises/1
  # GET /expertises/1.json
  def show
    @expertise = Expertise.find(params[:id])
    @user = @expertise.user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expertise }
    end
  end

  # GET /expertises/new
  # GET /expertises/new.json
  def new
    @expertise = Expertise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expertise }
    end
  end

  # GET /expertises/1/edit
  def edit
    @expertise = Expertise.find(params[:id])
  end

  # POST /expertises
  # POST /expertises.json
  def create
    @expertise = Expertise.new(params[:expertise])
    @expertise.user = current_user
    @expertise.positive = 0
    @expertise.negative = 0

    respond_to do |format|
      if @expertise.save
        format.html { redirect_to current_user, notice: 'Expertise was successfully created.' }
        format.json { render json: @expertise, status: :created, location: @expertise }
      else
        format.html { render action: "new" }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  def calificar
    @expertise = Expertise.find(params[:expertise_id])
    @votacion = Votacion.new
    @votacion.user_id = current_user.id
    @votacion.expertise_id = @expertise.id

    nota = params[:nota]

    if nota == "positivo"
      @expertise.positive += 1
    else 
      @expertise.negative += 1
    end



    if @votacion.save && @expertise.save
      redirect_to @expertise
    end
  end

  # PUT /expertises/1
  # PUT /expertises/1.json
  def update
    @expertise = Expertise.find(params[:id])

    respond_to do |format|
      if @expertise.update_attributes(params[:expertise])
        format.html { redirect_to @expertise, notice: 'Expertise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expertises/1
  # DELETE /expertises/1.json
  def destroy
    @expertise = Expertise.find(params[:id])
    @expertise.destroy

    respond_to do |format|
      format.html { redirect_to expertises_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/expertises_helper.rb
module ExpertisesHelper
end

app/views/expertises/_form.html.erb
  Siendo experto de un área, puedes validar las habilidades de otros usuarios.

  Recuerda que en EVALINK puedes registrarte como experto de un área, pero todos nuestros usuarios podrán calificar la credibilidad de ésto. Si nuestros usuarios creen que la información que pones es falta, perderás tu calidad de experto

  <br/>
  <br/>

<%= form_for(@expertise) do |f| %>
  <% if @expertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expertise.errors.count, "error") %> prohibited this expertise from being saved:</h2>

      <ul>
      <% @expertise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= f.label :area %></b><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <b><%= f.label :Institucion %></b><br/> Indica la institución en la que te desempeñas como experto<br />
    <%= f.text_field :institution %>
  </div>
  <div class="field">
    <b><%= f.label :cargo %></b><br/> Indica el cargo que tienes como experto. Por ej. ser profesor de una universidad<br />
    <%= f.text_field :cargo %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expertises/calificar.html.erb
<%= params %>

app/views/expertises/edit.html.erb
<h1>Editing expertise</h1>

<%= render 'form' %>

<%= link_to 'Show', @expertise %> |
<%= link_to 'Back', expertises_path %>

app/views/expertises/index.html.erb
<h1>Listing expertises</h1>

<table>
  <tr>
    <th>Area</th>
    <th>Positive</th>
    <th>Negative</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expertises.each do |expertise| %>
  <tr>
    <td><%= expertise.area %></td>
    <td><%= expertise.positive %></td>
    <td><%= expertise.negative %></td>
    <td><%= link_to 'Show', expertise %></td>
    <td><%= link_to 'Edit', edit_expertise_path(expertise) %></td>
    <td><%= link_to 'Destroy', expertise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expertise', new_expertise_path %>

app/views/expertises/new.html.erb
<h1>Nueva expertise</h1>

<%= render 'form' %>

app/views/expertises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Area:</b>
  <%= @expertise.area %>
</p>

<p>
  <b>Institución:</b>
  <%= @expertise.institution %>
</p>

<p>
  <b>Cargo:</b>
  <%= @expertise.cargo %>
</p>

<p>
  <b>Valoraciones positivas:</b>
  <%= @expertise.positive %>
</p>

<p>
  <b>Valoraciones negativas:</b>
  <%= @expertise.negative %>
</p>

<% if @user != current_user %>
  <h2> Calificar expertise </h2>
  <% if !current_user.has_voted?(@expertise) %>
    Califícala como positiva si consideras que los datos son verídicos y negativa si son falsos
  <%= form_tag("calificar", :method => "get") do %>
  <%= radio_button_tag(:nota, "positivo") %>
  <%= label_tag(:positivo, "Positivo") %>
  <%= radio_button_tag(:nota, "negativo") %>
  <%= label_tag(:negativo, "Negativo") %>
  <%= hidden_field_tag(:expertise_id, @expertise.id) %>
  <%= submit_tag("Calificar") %>
<% end %>
  <% else %>
    Ya calificaste esta expertise, no puedes hacerlo de nuevo.
  <% end %>
    

<% end %>