config/routes.rb
Evalink::Application.routes.draw do

  resources :companies

  get "/expertises/calificar" => "expertises#calificar", :as => "calificar_expertise"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "show_results" => "search#show_results", :as => "search_results"
  get "choose_jobs" => "search#choose_jobs", :as => "choose_jobs"
  get "choose_features" => "search#choose_features", :as => "choose_features"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "users#new"
  resources :users
  resources :sessions
  resources :abilities
  resources :expertises
  resources :validations

  get "sessions/new"

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  attr_accessible :description, :name, :area
  belongs_to :user
  has_many :validations


  def has_validations?
    validations != nil && validations != []
  end

end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  # GET /abilities
  # GET /abilities.json
  def index
    @abilities = Ability.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abilities }
    end
  end

  # GET /abilities/1
  # GET /abilities/1.json
  def show
    @ability = Ability.find(params[:id])
    @user = @ability.user
    @validations = @ability.validations

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ability }
    end
  end

  # GET /abilities/new
  # GET /abilities/new.json
  def new
    @ability = Ability.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ability }
    end
  end

  # GET /abilities/1/edit
  def edit
    @ability = Ability.find(params[:id])
  end

  # POST /abilities
  # POST /abilities.json
  def create
    @ability = Ability.new(params[:ability])
    @ability.user = current_user;

    respond_to do |format|
      if @ability.save
        format.html { redirect_to current_user, notice: 'Ability was successfully created.' }
        format.json { render json: @ability, status: :created, location: @ability }
      else
        format.html { render action: "new" }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /abilities/1
  # PUT /abilities/1.json
  def update
    @ability = Ability.find(params[:id])

    respond_to do |format|
      if @ability.update_attributes(params[:ability])
        format.html { redirect_to @ability, notice: 'Ability was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abilities/1
  # DELETE /abilities/1.json
  def destroy
    @ability = Ability.find(params[:id])
    @ability.destroy

    respond_to do |format|
      format.html { redirect_to abilities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/views/abilities/_form.html.erb
<%= form_for(@ability) do |f| %>
  <% if @ability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ability.errors.count, "error") %> prohibited this ability from being saved:</h2>

      <ul>
      <% @ability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abilities/edit.html.erb
<h1>Editing ability</h1>

<%= render 'form' %>

<%= link_to 'Show', @ability %> |
<%= link_to 'Back', abilities_path %>

app/views/abilities/index.html.erb
<h1>Listing abilities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @abilities.each do |ability| %>
  <tr>
    <td><%= ability.name %></td>
    <td><%= ability.description %></td>
    <td><%= link_to 'Show', ability %></td>
    <td><%= link_to 'Edit', edit_ability_path(ability) %></td>
    <td><%= link_to 'Destroy', ability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ability', new_ability_path %>

app/views/abilities/new.html.erb
<h1>New ability</h1>

<%= render 'form' %>

<%= link_to 'Back', abilities_path %>

app/views/abilities/show.html.erb
<p id="notice"><%= notice %></p>


  <h2><%= @ability.name %></h2>
  (Habilidad de <%= link_to "#{@user.first_name} #{@user.last_name}", @user %>)<br/>


  <b>Area:</b><br/>
  <%= @ability.area %>
</p>


<p>
  <b>Description:</b><br/>
  <%= @ability.description %>
</p>


<h2> Validaciones por expertos </h2>

<% if @user != current_user && current_user.is_expert?(@ability.area) && !current_user.has_validated?(@ability) %>
<b> Eres un experto en esta área, puedes <%=link_to "validarla",  new_validation_url(:ability_id => @ability.id) %> </b><br/>

<%end%>

<% if @ability.has_validations? %>
  Esta habilidad ha sido validada por los siguientes expertos.<br/>
  <% @validations.each do |v| %>
    <%= link_to "#{v.user.first_name} #{v.user.last_name}", v.user %>
  <%end%>
<%else%>
  <p> Esta habilidad no ha sido evaluada por expertos. </p>
<%end%>

<h2> Validaciones por tests </h2>

<p> Esta habilidad no ha sido validada por tests </p>